default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db/mydb_development.sqlite3

test:
  <<: *default
  database: db/mydb_test.sqlite3